handle_assets: true
handle_glide: true
advanced: false
optimizers:
  -
    mimetype: image/jpeg
    command: "{binary:jpegoptim} --strip-all --all-progressive -m85 :file"
  -
    mimetype: image/png
    command: "{binary:pngquant} --force :file --output=:file"
  -
    mimetype: image/png
    command: "{binary:optipng} -i0 -clobber -o5 :file"
  -
    mimetype: image/gif
    command: "{binary:gifsicle} -b -O3 :file"